2025-10-14 19:51:48 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: [32mнет ошибок :3[0m
2025-10-14 19:58:48 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: [32mнет ошибок :3[0m
2025-10-14 19:58:48 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: chat>> 5194033781 user>> HITHELL id>> 5194033781| сообщение >>
a
2025-10-14 20:54:27 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: [32mнет ошибок :3[0m
2025-10-14 21:01:15 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: [32mнет ошибок :3[0m
2025-10-14 21:01:15 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |ERROR: Ошибка: '>=' not supported between instances of 'str' and 'int' 
-----------------------------
Traceback (most recent call last):
  File "c:\Users\User\Desktop\file_telegram_mesenger\main.py", line 92, in main
    bot.polling(none_stop=True,timeout=30,long_polling_timeout=30,interval=1)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\User\Desktop\file_telegram_mesenger\main.py", line 73, in ls
    if size>=1024:
       ^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'

2025-10-14 21:02:41 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: [32mнет ошибок :3[0m
2025-10-14 21:02:41 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |ERROR: Ошибка: '>=' not supported between instances of 'str' and 'int' 
-----------------------------
Traceback (most recent call last):
  File "c:\Users\User\Desktop\file_telegram_mesenger\main.py", line 92, in main
    bot.polling(none_stop=True,timeout=30,long_polling_timeout=30,interval=1)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python313\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\User\Desktop\file_telegram_mesenger\main.py", line 73, in ls
    if size>=1024 and type(size) != str:
       ^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'

2025-10-14 21:03:10 |c:\Users\User\Desktop\file_telegram_mesenger\main.py| line:21 |info: [32mнет ошибок :3[0m
